spring:
  application:
    name: nowoj-backend

  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  session:
    store-type: redis
    timeout: 2592000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/now_oj
    username: root
    password: 123456

  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000

  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

codesandbox:
  type: remote